REM   Script: DBMS_UNIVERSITY_PROJECT
REM   MA

CREATE TABLE STUDENT (  
STUDENT_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15),  
LAST_NAME VARCHAR2(15),  
E_MAIL VARCHAR2(15), 
PRIMARY KEY(STUDENT_ID) 
);

CREATE TABLE COURSE (  
COURSE_ID VARCHAR2(10) NOT NULL, 
CREDITS NUMBER,  
NAME VARCHAR2(15),  
TYPE VARCHAR2(15),  
PRIMARY KEY(COURSE_ID) 
);

CREATE TABLE TEACHER (  
TEACHER_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
EXPERIENCE NUMBER,  
PRIMARY KEY(TEACHER_ID) 
);

CREATE TABLE BOOKS (  
BOOK_ID VARCHAR2(10) NOT NULL, 
PRICE NUMBER,  
NAME VARCHAR2(15), 
AUTHOR VARCHAR2(15), 
PRIMARY KEY(BOOK_ID) 
);

CREATE TABLE MENTOR (  
MENTOR_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
PRIMARY KEY(MENTOR_ID) 
);

CREATE TABLE DEPARTMENT (  
DEPARTMENT_ID VARCHAR2(10) NOT NULL, 
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
PH_NO NUMBER,  
HOD VARCHAR2(15), 
E_MAIL VARCHAR(25), 
PRIMARY KEY(DEPARTMENT_ID) 
);

select table_name 
from   user_tables;

DESC DEPARTMENT


CREATE TABLE EXAM (   
EXAM_ID VARCHAR2(15) NOT NULL,  
NO_OF_STU NUMBER,   
DOE VARCHAR2(15),   
NO_OF_ABS NUMBER,   
MALPRACTICE NUMBER,  
PRIMARY KEY(EXAM_ID) 
);

select table_name from user_tables;

DESC TEACHER


DESC COURSE


CREATE TABLE TEACHES (    
COURSE_ID VARCHAR2(10), 
TEACHER_ID VARCHAR2(10), 
constraint FK_TEACHES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID), 
constraint FK_TEACHES_TEACHES_ID foreign key (TEACHER_ID) references TEACHER(TEACHER_ID), 
CONSTRAINT PK_TEACHES PRIMARY KEY(COURSE_ID,TEACHER_ID) 
);

select table_name from user_tables;

CREATE TABLE BUYS (     
COURSE_ID VARCHAR2(10),  
BOOK_ID VARCHAR2(10), 
DATE_BUY DATE, 
constraint FK_BUYS_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_BUYS_BOOK_ID foreign key (BOOK_ID) references BOOKS(BOOK_ID),  
CONSTRAINT PK_BUYS PRIMARY KEY(COURSE_ID,BOOK_ID)  
);

CREATE TABLE TAKES (     
COURSE_ID VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_TAKES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_TAKES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_TAKES PRIMARY KEY(COURSE_ID,STUDENT_ID)  
);

desc buys


CREATE TABLE STU_COURSES (     
COURSE_IDS VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_STU_COURSES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_STU_COURSES PRIMARY KEY(COURSE_IDS,STUDENT_ID)  
);

select table_name from user_tables;

desc books


desc buys


desc course


desc department


desc exam


desc mentor


desc student


desc stu_courses


desc takes


desc teacher


desc teaches


desc mentor


INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('1',1500,'WEB_TECH','RAVI');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('2',1300,'DBMS','SAI');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('3',1400,'SOCIAL','DEERAJ');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('4',1250,'OOPS','RAMYA');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('5',1340,'HCI','JASHWANTH');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('6',900,'AOD','GOKUL');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('7',890,'STATS','DIVYA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1004',4,'DSA','ETH,ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1003',3,'DBMS','ETH');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1001',4,'DLM','ETH,ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1014',3,'HCI','ETH,EPJ');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1005',2,'SOFTWARE','ETH');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('CSE1002',3,'OOPS','ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('CSE1014',4,'JAVA','ETH,ELA');

desc department


ALTER TABLE DEPARTMENT DROP COLUMN LAST_NAME;

ALTER TABLE DEPARTMENT RENAME COLUMN FIRST_NAME TO D_NAME;

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('BIT1','IT',9876504321,'VISWANATHAN','BIT1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('CSE1','CSE',8706543219,'RAM','CSE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('BCE1','CSE_SPEC',8706512349,'PARIMALA','BCE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('EEE1','ELECTRONICS',9102345678,'VIJAYAN','EEE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('ECE1','ECE',8976504321,'BANSAL','ECE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('AER1','AERONATICAL',7896504321,'KERITH','AER1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('MIS1','M_TECH',9871234560,'CHERITH','MIS1@GMAIL.COM');

desc exam


INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX101',40,'2021-01-11',2,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX102',50,'2021-05-01',0,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX103',60,'2021-04-01',1,2);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX104',40,'2021-03-01',3,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX105',70,'2021-02-01',4,1);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX106',30,'2021-11-01',2,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX107',45,'2021-01-01',1,0);

ALTER TABLE STUDENT MODIFY(E_MAIL VARCHAR2(30));

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0001',9870541230,'SAI','PRANEETH','20BIT0001@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0002',9806541230,'RAM','DEERAJ','20BIT0002@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0003',9870541230,'SIN','ARI','20BIT0003@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0004',9876441230,'DIVS','DIYA','20BIT0004@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0005',9872541230,'HEY','RAMYA','20BIT0005@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0006',9376541230,'NANI','PAVAN','20BIT0006@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0007',9856541230,'KAVYA','GOKUL','20BIT0007@GMAIL.COM');

SELECT * FROM EXAM;

DESC BUYS


DROP TABLE BUYS;

CREATE TABLE BUYS (      
STUDENT_ID VARCHAR2(10),   
BOOK_ID VARCHAR2(10),  
DATE_BUY DATE,  
constraint FK_BUYS_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),   
constraint FK_BUYS_BOOK_ID foreign key (BOOK_ID) references BOOKS(BOOK_ID),   
CONSTRAINT PK_BUYS PRIMARY KEY(STUDENT_ID,BOOK_ID)   
);

DESC BUYS


INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0001','1','01-JAN-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0002','2','11-FEB-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0003','3','21-MAR-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0004','4','13-APR-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0005','5','14-MAY-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0006','6','01-JUN-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0007','7','11-JUL-21');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN1',9996665789,'DR.Surendhar','reddy','MEN1@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH1',9087654321,'DR.SUDHEER ','REDDY ','TEACH1@vit.ac.in ',20);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH2',8567654321,'DR.RAMA','SUNDHAR ','TEACH2@vit.ac.in',15);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH3',8967643210,'DR.RAVI','KUMAR ','TEACH3@vit.ac.in ',10);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH4',7967643210,'DR.SRINIVAS','REDDY ','TEACH4@vit.ac.in ',30);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH5',8867643210,'DR.RASHEED','REDDHY ',' TEACH5@vit.ac.in',5);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH6',8888643210,'DR.SURAJ',' REDDY',' TEACH6@vit.ac.in',23);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH7',8123643210,'DR.SAI','REDDY ',' TEACH7@vit.ac.in',1);

ALTER TABLE TEACHER MODIFY(E_MAIL VARCHAR2(30));

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH1',9087654321,'DR.SUDHEER ','REDDY ','TEACH1@vit.ac.in ',20);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH2',8567654321,'DR.RAMA','SUNDHAR ','TEACH2@vit.ac.in',15);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH3',8967643210,'DR.RAVI','KUMAR ','TEACH3@vit.ac.in ',10);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH4',7967643210,'DR.SRINIVAS','REDDY ','TEACH4@vit.ac.in ',30);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH5',8867643210,'DR.RASHEED','REDDHY ',' TEACH5@vit.ac.in',5);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH6',8888643210,'DR.SURAJ',' REDDY',' TEACH6@vit.ac.in',23);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH7',8123643210,'DR.SAI','REDDY ',' TEACH7@vit.ac.in',1);

SELECT * FROM COURSE;

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','TEACH1');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','TEACH2');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','TEACH3');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','TEACH4');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','TEACH5');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','TEACH6');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','TEACH7');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','20BIT007');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','TEACH1');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','TEACH2');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','TEACH3');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','TEACH4');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','TEACH5');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','TEACH6');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','TEACH7');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1014','20BIT007');

DESC TAKES


SELECT * FROM STUDENT;

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1001','20BIT0001');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1003','20BIT0002');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1005','20BIT0004');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1002','20BIT0005');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1014','20BIT0006');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1014','20BIT0007');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1004','20BIT0003');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1001','20BIT0001');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1003','20BIT0002');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1004','20BIT0003');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1005','20BIT0004');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1002','20BIT0005');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1014','20BIT0006');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1014','20BIT0007');

ALTER TABLE STUDENT MODIFY(STUDENT_ID VARCHAR2(11) NOT NULL);

ALTER TABLE COURSE MODIFY(COURSE_ID VARCHAR2(11) NOT NULL);

ALTER TABLE MENTOR MODIFY(E_MAIL VARCHAR2(31) NOT NULL);

ALTER TABLE TEACHER MODIFY(PH_NO NUMBER(10));

ALTER TABLE STUDENT MODIFY(STUDENT_ID VARCHAR2(11));

ALTER TABLE COURSE MODIFY(COURSE_ID VARCHAR2(11));

ALTER TABLE MENTOR MODIFY(E_MAIL VARCHAR2(31) NOT NULL);

ALTER TABLE TEACHER MODIFY(PH_NO NUMBER(20));

DELETE FROM TAKES WHERE STUDENT_ID='20BIT0007';

desc student


CREATE TABLE STUDENT (  
STUDENT_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15),  
LAST_NAME VARCHAR2(15),  
E_MAIL VARCHAR2(15), 
PRIMARY KEY(STUDENT_ID) 
);

CREATE TABLE COURSE (  
COURSE_ID VARCHAR2(10) NOT NULL, 
CREDITS NUMBER,  
NAME VARCHAR2(15),  
TYPE VARCHAR2(15),  
PRIMARY KEY(COURSE_ID) 
);

CREATE TABLE TEACHER (  
TEACHER_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
EXPERIENCE NUMBER,  
PRIMARY KEY(TEACHER_ID) 
);

CREATE TABLE BOOKS (  
BOOK_ID VARCHAR2(10) NOT NULL, 
PRICE NUMBER,  
NAME VARCHAR2(15), 
AUTHOR VARCHAR2(15), 
PRIMARY KEY(BOOK_ID) 
);

CREATE TABLE MENTOR (  
MENTOR_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
PRIMARY KEY(MENTOR_ID) 
);

CREATE TABLE DEPARTMENT (  
DEPARTMENT_ID VARCHAR2(10) NOT NULL, 
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
PH_NO NUMBER,  
HOD VARCHAR2(15), 
E_MAIL VARCHAR(25), 
PRIMARY KEY(DEPARTMENT_ID) 
);

select table_name 
from   user_tables;

DESC DEPARTMENT


CREATE TABLE EXAM (   
EXAM_ID VARCHAR2(15) NOT NULL,  
NO_OF_STU NUMBER,   
DOE VARCHAR2(15),   
NO_OF_ABS NUMBER,   
MALPRACTICE NUMBER,  
PRIMARY KEY(EXAM_ID) 
);

select table_name from user_tables;

DESC TEACHER


DESC COURSE


CREATE TABLE TEACHES (    
COURSE_ID VARCHAR2(10), 
TEACHER_ID VARCHAR2(10), 
constraint FK_TEACHES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID), 
constraint FK_TEACHES_TEACHES_ID foreign key (TEACHER_ID) references TEACHER(TEACHER_ID), 
CONSTRAINT PK_TEACHES PRIMARY KEY(COURSE_ID,TEACHER_ID) 
);

select table_name from user_tables;

CREATE TABLE BUYS (     
COURSE_ID VARCHAR2(10),  
BOOK_ID VARCHAR2(10), 
DATE_BUY DATE, 
constraint FK_BUYS_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_BUYS_BOOK_ID foreign key (BOOK_ID) references BOOKS(BOOK_ID),  
CONSTRAINT PK_BUYS PRIMARY KEY(COURSE_ID,BOOK_ID)  
);

CREATE TABLE TAKES (     
COURSE_ID VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_TAKES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_TAKES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_TAKES PRIMARY KEY(COURSE_ID,STUDENT_ID)  
);

desc buys


CREATE TABLE STU_COURSES (     
COURSE_IDS VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_STU_COURSES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_STU_COURSES PRIMARY KEY(COURSE_IDS,STUDENT_ID)  
);

select table_name from user_tables;

desc books


desc buys


desc course


desc department


desc exam


desc mentor


desc student


desc stu_courses


desc takes


desc teacher


desc teaches


desc mentor


INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('1',1500,'WEB_TECH','RAVI');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('2',1300,'DBMS','SAI');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('3',1400,'SOCIAL','DEERAJ');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('4',1250,'OOPS','RAMYA');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('5',1340,'HCI','JASHWANTH');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('6',900,'AOD','GOKUL');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('7',890,'STATS','DIVYA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1004',4,'DSA','ETH,ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1003',3,'DBMS','ETH');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1001',4,'DLM','ETH,ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1014',3,'HCI','ETH,EPJ');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1005',2,'SOFTWARE','ETH');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('CSE1002',3,'OOPS','ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('CSE1014',4,'JAVA','ETH,ELA');

desc department


ALTER TABLE DEPARTMENT DROP COLUMN LAST_NAME;

ALTER TABLE DEPARTMENT RENAME COLUMN FIRST_NAME TO D_NAME;

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('BIT1','IT',9876504321,'VISWANATHAN','BIT1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('CSE1','CSE',8706543219,'RAM','CSE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('BCE1','CSE_SPEC',8706512349,'PARIMALA','BCE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('EEE1','ELECTRONICS',9102345678,'VIJAYAN','EEE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('ECE1','ECE',8976504321,'BANSAL','ECE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('AER1','AERONATICAL',7896504321,'KERITH','AER1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('MIS1','M_TECH',9871234560,'CHERITH','MIS1@GMAIL.COM');

desc exam


INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX101',40,'2021-01-11',2,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX102',50,'2021-05-01',0,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX103',60,'2021-04-01',1,2);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX104',40,'2021-03-01',3,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX105',70,'2021-02-01',4,1);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX106',30,'2021-11-01',2,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX107',45,'2021-01-01',1,0);

ALTER TABLE STUDENT MODIFY(E_MAIL VARCHAR2(30));

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0001',9870541230,'SAI','PRANEETH','20BIT0001@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0002',9806541230,'RAM','DEERAJ','20BIT0002@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0003',9870541230,'SIN','ARI','20BIT0003@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0004',9876441230,'DIVS','DIYA','20BIT0004@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0005',9872541230,'HEY','RAMYA','20BIT0005@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0006',9376541230,'NANI','PAVAN','20BIT0006@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0007',9856541230,'KAVYA','GOKUL','20BIT0007@GMAIL.COM');

SELECT * FROM EXAM;

DESC BUYS


DROP TABLE BUYS;

CREATE TABLE BUYS (      
STUDENT_ID VARCHAR2(10),   
BOOK_ID VARCHAR2(10),  
DATE_BUY DATE,  
constraint FK_BUYS_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),   
constraint FK_BUYS_BOOK_ID foreign key (BOOK_ID) references BOOKS(BOOK_ID),   
CONSTRAINT PK_BUYS PRIMARY KEY(STUDENT_ID,BOOK_ID)   
);

DESC BUYS


INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0001','1','01-JAN-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0002','2','11-FEB-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0003','3','21-MAR-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0004','4','13-APR-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0005','5','14-MAY-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0006','6','01-JUN-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0007','7','11-JUL-21');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN1',9996665789,'DR.Surendhar','reddy','MEN1@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN1',9996665789,'DR.Surendhar','reddy','MEN1@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH1',9087654321,'DR.SUDHEER ','REDDY ','TEACH1@vit.ac.in ',20);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH2',8567654321,'DR.RAMA','SUNDHAR ','TEACH2@vit.ac.in',15);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH3',8967643210,'DR.RAVI','KUMAR ','TEACH3@vit.ac.in ',10);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH4',7967643210,'DR.SRINIVAS','REDDY ','TEACH4@vit.ac.in ',30);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH5',8867643210,'DR.RASHEED','REDDHY ',' TEACH5@vit.ac.in',5);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH6',8888643210,'DR.SURAJ',' REDDY',' TEACH6@vit.ac.in',23);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH7',8123643210,'DR.SAI','REDDY ',' TEACH7@vit.ac.in',1);

ALTER TABLE TEACHER MODIFY(E_MAIL VARCHAR2(30));

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH1',9087654321,'DR.SUDHEER ','REDDY ','TEACH1@vit.ac.in ',20);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH2',8567654321,'DR.RAMA','SUNDHAR ','TEACH2@vit.ac.in',15);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH3',8967643210,'DR.RAVI','KUMAR ','TEACH3@vit.ac.in ',10);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH4',7967643210,'DR.SRINIVAS','REDDY ','TEACH4@vit.ac.in ',30);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH5',8867643210,'DR.RASHEED','REDDHY ',' TEACH5@vit.ac.in',5);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH6',8888643210,'DR.SURAJ',' REDDY',' TEACH6@vit.ac.in',23);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH7',8123643210,'DR.SAI','REDDY ',' TEACH7@vit.ac.in',1);

SELECT * FROM COURSE;

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','TEACH1');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','TEACH2');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','TEACH3');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','TEACH4');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','TEACH5');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','TEACH6');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','TEACH7');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','20BIT007');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','TEACH1');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','TEACH2');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','TEACH3');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','TEACH4');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','TEACH5');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','TEACH6');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','TEACH7');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1014','20BIT007');

DESC TAKES


SELECT * FROM STUDENT;

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1014','20BIT0007');

ALTER TABLE STUDENT MODIFY(STUDENT_ID VARCHAR2(11));

ALTER TABLE COURSE MODIFY(COURSE_ID VARCHAR2(11));

DELETE FROM TAKES WHERE STUDENT_ID='20BIT0007';

DELETE FROM TEACHES WHERE TEACHER_ID='TEACH7';

DELETE FROM STU_COURSES WHERE STUDENT_ID='20BIT0007';

DELETE FROM BUYS WHERE BOOK_ID='7';

SELECT * FROM BOOKS;

SELECT * FROM EXAM;

UPDATE STUDENT SET FIRST_NAME = 'King'  WHERE STUDENT_ID = '20BIT0006';

UPDATE BOOKS SET NAME = 'King'  WHERE BOOK_ID = '6';

UPDATE EXAM SET NO_OF_ABS = 5  WHERE EXAM_ID = 'EX106';

UPDATE MENTOR SET FIRST_NAME = 'BIMAL'  WHERE MENTOR_ID = 'MEN6';

ALTER TABLE STUDENT ADD (CONSTRAINT STU_FK_M_ID  FOREIGN KEY (STU_FK_M_ID) REFERENCES MENTOR(MENTOR_ID));

DESC MENTOR


ALTER TABLE STUDENT ADD (M_ID VARCHAR2(10));

ALTER TABLE STUDENT ADD (M_ID VARCHAR2(10));

ALTER TABLE STUDENT ADD (  
  CONSTRAINT STU_FK_A  
  FOREIGN KEY (M_ID)   
  REFERENCES MENTOR(MENTOR_ID));

DESC DEPARTMENT


ALTER TABLE STUDENT ADD (D_ID VARCHAR2(10));

ALTER TABLE STUDENT ADD (CONSTRAINT STU_FK_A FOREIGN KEY (D_ID)  REFERENCES DEPARTMENT(DEPARTMENT_ID));

ALTER TABLE STUDENT ADD (CONSTRAINT STU_FK_D_ID FOREIGN KEY (D_ID)  REFERENCES DEPARTMENT(DEPARTMENT_ID));

ALTER TABLE COURSE ADD(D_ID VARCHAR2(10));

ALTER TABLE COURSE ADD (CONSTRAINT COURSE_FK_D_ID FOREIGN KEY (D_ID)  REFERENCES DEPARTMENT(DEPARTMENT_ID));

ALTER TABLE EXAM ADD(D_ID VARCHAR2(10));

ALTER TABLE EXAM ADD (CONSTRAINT EXAM_FK_D_ID FOREIGN KEY (D_ID)  REFERENCES DEPARTMENT(DEPARTMENT_ID));

SELECT FIRST_NAME,E_MAIL FROM STUDENT WHERE STUDENT_ID='20BIT0004';

SELECT NO_OF_STU,NO_OF_ABS FROM EXAM WHERE EXAM_ID='EX103';

SELECT PH_NO ,FIRST_NAME FROM MENTOR WHERE MENTOR_ID='MEN2';

SELECT FIRST_NAME,E_MAIL FROM TEACHER WHERE TEACHER_ID='TEACH2';

SELECT NAME,CREDITS,TYPE FROM COURSE ORDER BY NAME ASC;

SELECT FIRST_NAME,PH_NO FROM MENTOR ORDER BY MENTOR_ID DESC;

SELECT MALPRACTICE,E_MAIL FROM EXAM ORDER BY EXAM_ID ASC;

SELECT FIRST_NAME,LAST_NAME FROM MENTOR WHERE FIRST_NAME LIKE '%A%' ORDER BY LAST_NAME;

SELECT FIRST_NAME,LAST_NAME FROM STUDENT WHERE LAST_NAME LIKE '%S%' ORDER BY LAST_NAME;

SELECT FIRST_NAME,LAST_NAME FROM TEACHER WHERE FIRST_NAME LIKE '%E%' ORDER BY LAST_NAME;

DESC STUDENT


SELECT PH_NO,DEPARTMENT_ID FROM DEPARTMENT WHERE PH_NO IS NULL;

SELECT NAME,TYPE FROM COURSE WHERE TYPE IS NULL;

SELECT PH_NO,DEPARTMENT_ID FROM DEPARTMENT WHERE PH_NO IS NOT NULL;

SELECT NAME,TYPE FROM COURSE WHERE TYPE IS NOT NULL;

SELECT AVG(NO_OF_STU), AVG(DISTINCT NO_OF_STU) FROM EXAM;

SELECT MIN (NO_OF_STU), MIN (DISTINCT NO_OF_STU) FROM EXAM;

SELECT STDDEV(CREDITS), STDDEV(DISTINCT CREDITS) FROM COURSE;

SELECT VARIANCE(NO_OF_ABS), VARIANCE(DISTINCT NO_OF_ABS) FROM EXAM;

SELECT COUNT(MALRACTICE), COUNT(DISTINCT MALPRACTICE) FROM EXAM;

select max(NO_OF_ABS) from EXAM;

select avg(NO_OF_STU) as "Average NUMBER of STUDENTS" from EXAM;

DESC BUYS


DESC EXAM


ALTER TABLE EXAM DROP COLUMN DOE;

ALTER TABLE EXAM ADD (DOE DATE);

SELECT * FROM EXAM;

SELECT * FROM BUYS;

select date("01-JAN-2021");

select date("01-JAN-2021");

select ADD DATE(Date Of Join,50) from BUYS;

DESC BUYS


select date'01-jan-2021' DATE_BUY from EXAM;

select date'01-JAN-2021' DATE_BUY from EXAM;

select date'01-01-2021' DATE_BUY from EXAM;

select date'1-01-2021' DATE_BUY from EXAM;

select date'1-1-2021' DATE_BUY from EXAM;

select date'1-1-21' DATE_BUY from EXAM;

select to_char(d, 'dd-mm-yyyy') day_month_year,  
       to_char(d, 'hh24:mi') time_only,  
       to_char(d, 'iw-iyyy') iso_week_and_year,  
       to_char(d, 'Month') month_name  
from   BUYS;

select to_char(DATE_BUY, 'dd-mm-yyyy') day_month_year,  
       to_char(DATE_BUY, 'hh24:mi') time_only,  
       to_char(DATE_BUY, 'iw-iyyy') iso_week_and_year,  
       to_char(DATE_BUY, 'Month') month_name  
from   BUYS;

select DOE,  
       to_char(DOE, '9,999,999.99'),  
       to_char(DOE),  
       to_char(DOE, '0,000,000.000')  
from   EXAM;

SELECT EXAM_ID AS "EXAM", floor(sum(MALPRACTICE)) as "Total Students in Malpractice",Count(EXAM_ID) as "Number of EXAMS" from EXAM group by EXAM_ID;

SELECT EXAM_Id AS "EACH EXAM",FLOOR(SUM(NO_OF_STU)) as "NUMBER OF STUDENTS ",Count(NO_OF_ABS) AS "NUMBER OF ABSENT" FROM EXAM GROUP BY EXAM_ID_Id HAVING COUNT(MALPRACTICE)>3;

SELECT EXAM_Id AS "EACH EXAM",FLOOR(SUM(NO_OF_STU)) as "NUMBER OF STUDENTS ",Count(NO_OF_ABS) AS "NUMBER OF ABSENT" FROM EXAM GROUP BY EXAM_ID HAVING COUNT(MALPRACTICE)>3;

SELECT EXAM_Id AS "EACH EXAM",FLOOR(SUM(NO_OF_STU)) as "NUMBER OF STUDENTS ",Count(NO_OF_ABS) AS "NUMBER OF ABSENT" FROM EXAM GROUP BY EXAM_ID HAVING COUNT(MALPRACTICE)>0;

SELECT BOOK_ID,DAYNAME(DATE_BUY) FROM BUYS;

SELECT BOOK_ID,DAY NAME(DATE_BUY) FROM BUYS;

SELECT NAME,ceil(PRICE) from Books;

SELECT NAME,floor(log(PRICE)) from Books;

SELECT NAME,floor(sqrt(PRICE)) from Books;

SELECT NAME,truncate(sqrt(PRICE),2) from Books;

SELECT NAME,ceil(PRICE) from Books;

SELECT NAME,floor(log(PRICE)) from Books;

SELECT NAME,floor(sqrt(PRICE)) from Books;

SELECT NAME,TRUNCATE(sqrt(PRICE),2) from Books;

SELECT NAME,ceil(PRICE) from Books;

SELECT GREATEST(PRICE) FROM BOOKS;

SELECT NAME,floor(sqrt(PRICE)) from Books;

SELECT NAME,TRUNCATE(CEIL(PRICE),2) from Books;

SELECT NAME,ceil(PRICE) from Books;

SELECT GREATEST(PRICE) FROM BOOKS;

SELECT NAME,floor(sqrt(PRICE)) from Books;

SELECT ROUND(PRICE, 2) FROM BOOKS;

select NAME,length(NAME) as "BOOK NAME LENGTH" from Books;

select concat("NAME:-",FIRST_NAME," ",LAST_NAME) from TEACHER;

select trim(D_Name),trim(HOD) from DEPARTMENT;

select trim(D_Name),trim(HOD) from DEPARTMENT;

DESC EXAM


select substring(FIRST_Name,1,3) from STUDENT;

select replace(LAST_Name,"KING","KINGB") from STUDENT;

select reverse(substring(FIRST_Name,1,2)) from TEACHER;

DESC EXAM


SELECT * FROM STUDENT;

SELECT * FROM STUDENT;

select * from buys;

select * from buys;

SELECT * FROM COURSE;

SELECT * FROM COURSE;

desc student


desc student


SELECT * FROM TEACHER;

CREATE TABLE STUDENT (  
STUDENT_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15),  
LAST_NAME VARCHAR2(15),  
E_MAIL VARCHAR2(15), 
PRIMARY KEY(STUDENT_ID) 
);

SELECT * FROM TEACHER;

CREATE TABLE STUDENT (  
STUDENT_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15),  
LAST_NAME VARCHAR2(15),  
E_MAIL VARCHAR2(15), 
PRIMARY KEY(STUDENT_ID) 
);

SELECT * FROM BOOKS;

CREATE TABLE COURSE (  
COURSE_ID VARCHAR2(10) NOT NULL, 
CREDITS NUMBER,  
NAME VARCHAR2(15),  
TYPE VARCHAR2(15),  
PRIMARY KEY(COURSE_ID) 
);

SELECT * FROM BOOKS;

CREATE TABLE COURSE (  
COURSE_ID VARCHAR2(10) NOT NULL, 
CREDITS NUMBER,  
NAME VARCHAR2(15),  
TYPE VARCHAR2(15),  
PRIMARY KEY(COURSE_ID) 
);

SELECT * FROM MENTOR;

CREATE TABLE TEACHER (  
TEACHER_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
EXPERIENCE NUMBER,  
PRIMARY KEY(TEACHER_ID) 
);

SELECT * FROM MENTOR;

CREATE TABLE TEACHER (  
TEACHER_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
EXPERIENCE NUMBER,  
PRIMARY KEY(TEACHER_ID) 
);

SELECT * FROM DEPARTMENT;

CREATE TABLE BOOKS (  
BOOK_ID VARCHAR2(10) NOT NULL, 
PRICE NUMBER,  
NAME VARCHAR2(15), 
AUTHOR VARCHAR2(15), 
PRIMARY KEY(BOOK_ID) 
);

SELECT * FROM DEPARTMENT;

CREATE TABLE BOOKS (  
BOOK_ID VARCHAR2(10) NOT NULL, 
PRICE NUMBER,  
NAME VARCHAR2(15), 
AUTHOR VARCHAR2(15), 
PRIMARY KEY(BOOK_ID) 
);

SELECT * FROM EXAM;

CREATE TABLE MENTOR (  
MENTOR_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
PRIMARY KEY(MENTOR_ID) 
);

SELECT * FROM EXAM;

CREATE TABLE MENTOR (  
MENTOR_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
PRIMARY KEY(MENTOR_ID) 
);

SELECT * FROM TEACHES;

CREATE TABLE DEPARTMENT (  
DEPARTMENT_ID VARCHAR2(10) NOT NULL, 
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
PH_NO NUMBER,  
HOD VARCHAR2(15), 
E_MAIL VARCHAR(25), 
PRIMARY KEY(DEPARTMENT_ID) 
);

SELECT * FROM TEACHES;

CREATE TABLE DEPARTMENT (  
DEPARTMENT_ID VARCHAR2(10) NOT NULL, 
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
PH_NO NUMBER,  
HOD VARCHAR2(15), 
E_MAIL VARCHAR(25), 
PRIMARY KEY(DEPARTMENT_ID) 
);

SELECT * FROM BUYS;

SELECT * FROM BUYS;

select table_name 
from   user_tables;

select table_name 
from   user_tables;

SELECT * FROM TAKES;

SELECT * FROM TAKES;

DESC DEPARTMENT


DESC DEPARTMENT


SELECT * FROM STU_COURSES;

SELECT * FROM STU_COURSES;

CREATE TABLE EXAM (   
EXAM_ID VARCHAR2(15) NOT NULL,  
NO_OF_STU NUMBER,   
DOE VARCHAR2(15),   
NO_OF_ABS NUMBER,   
MALPRACTICE NUMBER,  
PRIMARY KEY(EXAM_ID) 
);

select table_name from user_tables;

DESC TEACHER


DESC COURSE


CREATE TABLE TEACHES (    
COURSE_ID VARCHAR2(10), 
TEACHER_ID VARCHAR2(10), 
constraint FK_TEACHES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID), 
constraint FK_TEACHES_TEACHES_ID foreign key (TEACHER_ID) references TEACHER(TEACHER_ID), 
CONSTRAINT PK_TEACHES PRIMARY KEY(COURSE_ID,TEACHER_ID) 
);

select table_name from user_tables;

CREATE TABLE BUYS (     
COURSE_ID VARCHAR2(10),  
BOOK_ID VARCHAR2(10), 
DATE_BUY DATE, 
constraint FK_BUYS_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_BUYS_BOOK_ID foreign key (BOOK_ID) references BOOKS(BOOK_ID),  
CONSTRAINT PK_BUYS PRIMARY KEY(COURSE_ID,BOOK_ID)  
);

CREATE TABLE TAKES (     
COURSE_ID VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_TAKES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_TAKES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_TAKES PRIMARY KEY(COURSE_ID,STUDENT_ID)  
);

desc buys


CREATE TABLE STU_COURSES (     
COURSE_IDS VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_STU_COURSES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_STU_COURSES PRIMARY KEY(COURSE_IDS,STUDENT_ID)  
);

select table_name from user_tables;

desc books


desc buys


desc course


desc department


desc exam


desc mentor


desc student


desc stu_courses


desc takes


desc teacher


desc teaches


desc mentor


INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('1',1500,'WEB_TECH','RAVI');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('2',1300,'DBMS','SAI');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('3',1400,'SOCIAL','DEERAJ');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('4',1250,'OOPS','RAMYA');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('5',1340,'HCI','JASHWANTH');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('6',900,'AOD','GOKUL');

INSERT INTO BOOKS (BOOK_ID,PRICE,NAME,AUTHOR) values ('7',890,'STATS','DIVYA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1004',4,'DSA','ETH,ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1003',3,'DBMS','ETH');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1001',4,'DLM','ETH,ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1014',3,'HCI','ETH,EPJ');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('ITE1005',2,'SOFTWARE','ETH');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('CSE1002',3,'OOPS','ELA');

INSERT INTO COURSE (COURSE_ID,CREDITS,NAME,TYPE) values ('CSE1014',4,'JAVA','ETH,ELA');

desc department


ALTER TABLE DEPARTMENT DROP COLUMN LAST_NAME;

ALTER TABLE DEPARTMENT RENAME COLUMN FIRST_NAME TO D_NAME;

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('BIT1','IT',9876504321,'VISWANATHAN','BIT1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('CSE1','CSE',8706543219,'RAM','CSE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('BCE1','CSE_SPEC',8706512349,'PARIMALA','BCE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('EEE1','ELECTRONICS',9102345678,'VIJAYAN','EEE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('ECE1','ECE',8976504321,'BANSAL','ECE1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('AER1','AERONATICAL',7896504321,'KERITH','AER1@GMAIL.COM');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,D_NAME,PH_NO,HOD,E_MAIL)  
VALUES ('MIS1','M_TECH',9871234560,'CHERITH','MIS1@GMAIL.COM');

desc exam


INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX101',40,'2021-01-11',2,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX102',50,'2021-05-01',0,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX103',60,'2021-04-01',1,2);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX104',40,'2021-03-01',3,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX105',70,'2021-02-01',4,1);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX106',30,'2021-11-01',2,0);

INSERT INTO EXAM (EXAM_ID,NO_OF_STU,DOE,NO_OF_ABS,MALPRACTICE)  
VALUES ('EX107',45,'2021-01-01',1,0);

ALTER TABLE STUDENT MODIFY(E_MAIL VARCHAR2(30));

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0001',9870541230,'SAI','PRANEETH','20BIT0001@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0002',9806541230,'RAM','DEERAJ','20BIT0002@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0003',9870541230,'SIN','ARI','20BIT0003@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0004',9876441230,'DIVS','DIYA','20BIT0004@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0005',9872541230,'HEY','RAMYA','20BIT0005@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0006',9376541230,'NANI','PAVAN','20BIT0006@GMAIL.COM');

INSERT INTO STUDENT (STUDENT_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('20BIT0007',9856541230,'KAVYA','GOKUL','20BIT0007@GMAIL.COM');

SELECT * FROM EXAM;

DESC BUYS


DROP TABLE BUYS;

CREATE TABLE BUYS (      
STUDENT_ID VARCHAR2(10),   
BOOK_ID VARCHAR2(10),  
DATE_BUY DATE,  
constraint FK_BUYS_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),   
constraint FK_BUYS_BOOK_ID foreign key (BOOK_ID) references BOOKS(BOOK_ID),   
CONSTRAINT PK_BUYS PRIMARY KEY(STUDENT_ID,BOOK_ID)   
);

DESC BUYS


INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0001','1','01-JAN-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0002','2','11-FEB-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0003','3','21-MAR-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0004','4','13-APR-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0005','5','14-MAY-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0006','6','01-JUN-21');

INSERT INTO BUYS (STUDENT_ID,BOOK_ID,DATE_BUY) VALUES ('20BIT0007','7','11-JUL-21');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN1',9996665789,'DR.Surendhar','reddy','MEN1@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN1',9996665789,'DR.Surendhar','reddy','MEN1@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRSTNAME,LAST_NAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN2',7806665789,'DR.chandrababu','naidu','MEN2@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN3',7006665700,'Dheeran','guptha','MEN3@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN4',9996665700,'DR.SRIRAM','CHANDRA','MEN4@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN5',9008765700,'DR.Sheker','Reddy','MEN5@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN6',9118765700,'Dr.routhu','praneeth','MEN6@vit.ac.in');

INSERT INTO MENTOR (MENTOR_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL)  
VALUES ('MEN7',8118765700,'DR.rama','devi','MEN7@vit.ac.in');

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH1',9087654321,'DR.SUDHEER ','REDDY ','TEACH1@vit.ac.in ',20);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH2',8567654321,'DR.RAMA','SUNDHAR ','TEACH2@vit.ac.in',15);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH3',8967643210,'DR.RAVI','KUMAR ','TEACH3@vit.ac.in ',10);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH4',7967643210,'DR.SRINIVAS','REDDY ','TEACH4@vit.ac.in ',30);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH5',8867643210,'DR.RASHEED','REDDHY ',' TEACH5@vit.ac.in',5);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH6',8888643210,'DR.SURAJ',' REDDY',' TEACH6@vit.ac.in',23);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRSTNAME,LASTNAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH7',8123643210,'DR.SAI','REDDY ',' TEACH7@vit.ac.in',1);

ALTER TABLE TEACHER MODIFY(E_MAIL VARCHAR2(30));

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH1',9087654321,'DR.SUDHEER ','REDDY ','TEACH1@vit.ac.in ',20);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH2',8567654321,'DR.RAMA','SUNDHAR ','TEACH2@vit.ac.in',15);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH3',8967643210,'DR.RAVI','KUMAR ','TEACH3@vit.ac.in ',10);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH4',7967643210,'DR.SRINIVAS','REDDY ','TEACH4@vit.ac.in ',30);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH5',8867643210,'DR.RASHEED','REDDHY ',' TEACH5@vit.ac.in',5);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH6',8888643210,'DR.SURAJ',' REDDY',' TEACH6@vit.ac.in',23);

INSERT INTO TEACHER (TEACHER_ID,PH_NO,FIRST_NAME,LAST_NAME,E_MAIL,EXPERIENCE)  
VALUES ('TEACH7',8123643210,'DR.SAI','REDDY ',' TEACH7@vit.ac.in',1);

SELECT * FROM COURSE;

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','TEACH1');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','TEACH2');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','TEACH3');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','TEACH4');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','TEACH5');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','TEACH6');

INSERT INTO TEACHES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','TEACH7');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','20BIT007');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1001','TEACH1');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1003','TEACH2');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1004','TEACH3');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1005','TEACH4');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1002','TEACH5');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('CSE1014','TEACH6');

INSERT INTO TAKES(COURSE_ID,TEACHER_ID) VALUES ('ITE1014','TEACH7');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1014','20BIT007');

DESC TAKES


SELECT * FROM STUDENT;

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1001','20BIT0001');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1003','20BIT0002');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1005','20BIT0004');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1002','20BIT0005');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('CSE1014','20BIT0006');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1014','20BIT0007');

INSERT INTO TAKES(COURSE_ID,STUDENT_ID) VALUES ('ITE1004','20BIT0003');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1001','20BIT001');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1003','20BIT002');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1004','20BIT003');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1005','20BIT004');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1002','20BIT005');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1014','20BIT006');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1014','20BIT007');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1001','20BIT0001');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1003','20BIT0002');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1004','20BIT0003');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1005','20BIT0004');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1002','20BIT0005');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('CSE1014','20BIT0006');

INSERT INTO STU_COURSES(COURSE_IDS,STUDENT_ID) VALUES ('ITE1014','20BIT0007');

ALTER TABLE STUDENT MODIFY(STUDENT_ID VARCHAR2(11) NOT NULL);

ALTER TABLE COURSE MODIFY(COURSE_ID VARCHAR2(11) NOT NULL);

ALTER TABLE MENTOR MODIFY(E_MAIL VARCHAR2(31) NOT NULL);

ALTER TABLE TEACHER MODIFY(PH_NO NUMBER(10));

ALTER TABLE STUDENT MODIFY(STUDENT_ID VARCHAR2(11));

ALTER TABLE COURSE MODIFY(COURSE_ID VARCHAR2(11));

ALTER TABLE MENTOR MODIFY(E_MAIL VARCHAR2(31) NOT NULL);

ALTER TABLE TEACHER MODIFY(PH_NO NUMBER(20));

DELETE FROM TAKES WHERE STUDENT_ID='20BIT0007';

desc student


CREATE TABLE STUDENT (  
STUDENT_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15),  
LAST_NAME VARCHAR2(15),  
E_MAIL VARCHAR2(15), 
PRIMARY KEY(STUDENT_ID) 
);

CREATE TABLE COURSE (  
COURSE_ID VARCHAR2(10) NOT NULL, 
CREDITS NUMBER,  
NAME VARCHAR2(15),  
TYPE VARCHAR2(15),  
PRIMARY KEY(COURSE_ID) 
);

CREATE TABLE TEACHER (  
TEACHER_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
EXPERIENCE NUMBER,  
PRIMARY KEY(TEACHER_ID) 
);

CREATE TABLE BOOKS (  
BOOK_ID VARCHAR2(10) NOT NULL, 
PRICE NUMBER,  
NAME VARCHAR2(15), 
AUTHOR VARCHAR2(15), 
PRIMARY KEY(BOOK_ID) 
);

CREATE TABLE MENTOR (  
MENTOR_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
PRIMARY KEY(MENTOR_ID) 
);

CREATE TABLE DEPARTMENT (  
DEPARTMENT_ID VARCHAR2(10) NOT NULL, 
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
PH_NO NUMBER,  
HOD VARCHAR2(15), 
E_MAIL VARCHAR(25), 
PRIMARY KEY(DEPARTMENT_ID) 
);

select table_name 
from   user_tables;

DESC DEPARTMENT


CREATE TABLE EXAM (   
EXAM_ID VARCHAR2(15) NOT NULL,  
NO_OF_STU NUMBER,   
DOE VARCHAR2(15),   
NO_OF_ABS NUMBER,   
MALPRACTICE NUMBER,  
PRIMARY KEY(EXAM_ID) 
);

select table_name from user_tables;

DESC TEACHER


DESC EXAM


select * from buys;

desc student


CREATE TABLE STUDENT (  
STUDENT_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15),  
LAST_NAME VARCHAR2(15),  
E_MAIL VARCHAR2(15), 
PRIMARY KEY(STUDENT_ID) 
);

CREATE TABLE COURSE (  
COURSE_ID VARCHAR2(10) NOT NULL, 
CREDITS NUMBER,  
NAME VARCHAR2(15),  
TYPE VARCHAR2(15),  
PRIMARY KEY(COURSE_ID) 
);

CREATE TABLE TEACHER (  
TEACHER_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
EXPERIENCE NUMBER,  
PRIMARY KEY(TEACHER_ID) 
);

CREATE TABLE BOOKS (  
BOOK_ID VARCHAR2(10) NOT NULL, 
PRICE NUMBER,  
NAME VARCHAR2(15), 
AUTHOR VARCHAR2(15), 
PRIMARY KEY(BOOK_ID) 
);

CREATE TABLE MENTOR (  
MENTOR_ID VARCHAR2(10) NOT NULL, 
PH_NO NUMBER,  
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
E_MAIL VARCHAR2(15), 
PRIMARY KEY(MENTOR_ID) 
);

CREATE TABLE DEPARTMENT (  
DEPARTMENT_ID VARCHAR2(10) NOT NULL, 
FIRST_NAME VARCHAR2(15), 
LAST_NAME VARCHAR2(15), 
PH_NO NUMBER,  
HOD VARCHAR2(15), 
E_MAIL VARCHAR(25), 
PRIMARY KEY(DEPARTMENT_ID) 
);

select table_name 
from   user_tables;

DESC DEPARTMENT


CREATE TABLE EXAM (   
EXAM_ID VARCHAR2(15) NOT NULL,  
NO_OF_STU NUMBER,   
DOE VARCHAR2(15),   
NO_OF_ABS NUMBER,   
MALPRACTICE NUMBER,  
PRIMARY KEY(EXAM_ID) 
);

select table_name from user_tables;

DESC TEACHER


DESC COURSE


CREATE TABLE TEACHES (    
COURSE_ID VARCHAR2(10), 
TEACHER_ID VARCHAR2(10), 
constraint FK_TEACHES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID), 
constraint FK_TEACHES_TEACHES_ID foreign key (TEACHER_ID) references TEACHER(TEACHER_ID), 
CONSTRAINT PK_TEACHES PRIMARY KEY(COURSE_ID,TEACHER_ID) 
);

select table_name from user_tables;

CREATE TABLE BUYS (     
COURSE_ID VARCHAR2(10),  
BOOK_ID VARCHAR2(10), 
DATE_BUY DATE, 
constraint FK_BUYS_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_BUYS_BOOK_ID foreign key (BOOK_ID) references BOOKS(BOOK_ID),  
CONSTRAINT PK_BUYS PRIMARY KEY(COURSE_ID,BOOK_ID)  
);

CREATE TABLE TAKES (     
COURSE_ID VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_TAKES_COURSE_ID foreign key (COURSE_ID) references COURSE(COURSE_ID),  
constraint FK_TAKES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_TAKES PRIMARY KEY(COURSE_ID,STUDENT_ID)  
);

desc buys


CREATE TABLE STU_COURSES (     
COURSE_IDS VARCHAR2(10),  
STUDENT_ID VARCHAR2(10), 
constraint FK_STU_COURSES_STUDENT_ID foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),  
CONSTRAINT PK_STU_COURSES PRIMARY KEY(COURSE_IDS,STUDENT_ID)  
);

select table_name from user_tables;

desc books


desc buys


desc course


desc department


desc exam


desc mentor


desc student


desc stu_courses


desc takes


desc teacher


desc teaches


desc mentor


desc student


desc student


select substr(FIRST_Name,1,2) from STUDENT;

select reverse(substr(LAST_Name,1,3)) from TEACHER;

select concat("Name :- ",FIRST_Name,"  ",LAST_NAME) from TEACHER;

select concat(FIRST_Name,LAST_NAME) from TEACHER;

select concat(FIRST_Name," ",LAST_NAME) from TEACHER;

select concat(FIRST_Name,LAST_NAME) from TEACHER;

select STUDENT.FIRST_Name,Books.Name from STUDENT,BOOKS;

select STUDENT.FIRST_Name,Books.Name from STUDENT NATURAL JOIN BOOKS;

SELECT STUDENT.FIRST_Name,BUYS.BOOK_ID,STU_COURSES.COURSE_IDS from STUDENT 
natural join BUYS natural join STU_COURSES where BUYS.STUDENT_Id=STUDENT.STUDENT_Id and  
STUDENT.STUDENT_Id=STU_COURSES.STUDENT_Id ;

SELECT STUDENT.FIRST_Name,BUYS.BOOK_ID,STU_COURSES.COURSE_IDS from BUYS 
natural join STUDENT natural join STU_COURSES where BUYS.STUDENT_Id=STUDENT.STUDENT_Id and  
STUDENT.STUDENT_Id=STU_COURSES.STUDENT_Id ;

SELECT STUDENT.FIRST_Name,BUYS.BOOK_ID,STU_COURSES.COURSE_IDS from BUYS, 
STUDENT , STU_COURSES where BUYS.STUDENT_Id=STUDENT.STUDENT_Id and  
STUDENT.STUDENT_Id=STU_COURSES.STUDENT_Id ;

